-- Generated by translate.py; do not edit.
-- Input SHA-256: f43285cc98e81b74d2f2d651a7545d29e94026fa2201944d0aafc00ee2262141
import Machine

namespace Kernel
open Assembly

def program : Program := #[
  .vsetvli 14 0 32 8 .agnostic, -- pc=0, source line=11
  .vmvVI 8 0, -- pc=1, source line=12
  .branch .eq 10 0 10, -- pc=2, source line=13
  .vsetvli 15 10 32 8 .undisturbed, -- pc=3, source line=15
  .vle8 2 11, -- pc=4, source line=16
  .alu .sub 10 10 15, -- pc=5, source line=17
  .alu .add 11 11 15, -- pc=6, source line=18
  .vzextVF4 16 2, -- pc=7, source line=19
  .vaddVV 8 8 16, -- pc=8, source line=20
  .branch .ne 10 0 3, -- pc=9, source line=21
  .vsetvli 15 0 32 1 .agnostic, -- pc=10, source line=23
  .vmvVI 1 0, -- pc=11, source line=24
  .vsetvli 14 0 32 8 .agnostic, -- pc=12, source line=25
  .loadWord 13 12 0, -- pc=13, source line=26
  .vredsumVS 8 8 1, -- pc=14, source line=27
  .vmvXS 15 8, -- pc=15, source line=28
  .alu .addw 15 15 13, -- pc=16, source line=29
  .storeWord 15 12 0, -- pc=17, source line=30
  .ret -- pc=18, source line=31
]

end Kernel
