Require Import isla.riscv64.riscv64 RvvLoadSharedDefs RvvUpdateExpressions RvvAllUpdatesFast RvvTaggedCache.
Local Opaque load_update_value_0 load_update_value_1 load_update_value_2 load_update_value_3 load_update_value_4 load_update_value_5 load_update_value_6 load_update_value_7 load_update_value_8 load_update_value_9 load_update_value_10 load_update_value_11 load_update_value_12 load_update_value_13 load_update_value_14 load_update_value_15 load_update_value_16 load_update_value_17 load_update_value_18 load_update_value_19 load_update_value_20 load_update_value_21 load_update_value_22 load_update_value_23 load_update_value_24 load_update_value_25 load_update_value_26 load_update_value_27 load_update_value_28 load_update_value_29 load_update_value_30 load_update_value_31.
Lemma vector_value_eq_elim x y : vector_value_eq x y -> x = y.
Proof. intros [H]. exact H. Qed.
Lemma load_case_value_0 old (f : N -> bv 8) :
 (load_update_value_31 (load_update_value_30 (load_update_value_29 (load_update_value_28 (load_update_value_27 (load_update_value_26 (load_update_value_25 (load_update_value_24 (load_update_value_23 (load_update_value_22 (load_update_value_21 (load_update_value_20 (load_update_value_19 (load_update_value_18 (load_update_value_17 (load_update_value_16 (load_update_value_15 (load_update_value_14 (load_update_value_13 (load_update_value_12 (load_update_value_11 (load_update_value_10 (load_update_value_9 (load_update_value_8 (load_update_value_7 (load_update_value_6 (load_update_value_5 (load_update_value_4 (load_update_value_3 (load_update_value_2 (load_update_value_1 (load_update_value_0 old (bv_extract 0%N 8 old)) (bv_extract 8%N 8 old)) (bv_extract 16%N 8 old)) (bv_extract 24%N 8 old)) (bv_extract 32%N 8 old)) (bv_extract 40%N 8 old)) (bv_extract 48%N 8 old)) (bv_extract 56%N 8 old)) (bv_extract 64%N 8 old)) (bv_extract 72%N 8 old)) (bv_extract 80%N 8 old)) (bv_extract 88%N 8 old)) (bv_extract 96%N 8 old)) (bv_extract 104%N 8 old)) (bv_extract 112%N 8 old)) (bv_extract 120%N 8 old)) (bv_extract 128%N 8 old)) (bv_extract 136%N 8 old)) (bv_extract 144%N 8 old)) (bv_extract 152%N 8 old)) (bv_extract 160%N 8 old)) (bv_extract 168%N 8 old)) (bv_extract 176%N 8 old)) (bv_extract 184%N 8 old)) (bv_extract 192%N 8 old)) (bv_extract 200%N 8 old)) (bv_extract 208%N 8 old)) (bv_extract 216%N 8 old)) (bv_extract 224%N 8 old)) (bv_extract 232%N 8 old)) (bv_extract 240%N 8 old)) (bv_extract 248%N 8 old)) = loaded8 (BV 64 0) old f.
Proof. rewrite <- load_all_updates_correct_fast. reflexivity. Qed.
Print Assumptions load_case_value_0.
Lemma load_case_value_1 old (f : N -> bv 8) :
 (load_update_value_31 (load_update_value_30 (load_update_value_29 (load_update_value_28 (load_update_value_27 (load_update_value_26 (load_update_value_25 (load_update_value_24 (load_update_value_23 (load_update_value_22 (load_update_value_21 (load_update_value_20 (load_update_value_19 (load_update_value_18 (load_update_value_17 (load_update_value_16 (load_update_value_15 (load_update_value_14 (load_update_value_13 (load_update_value_12 (load_update_value_11 (load_update_value_10 (load_update_value_9 (load_update_value_8 (load_update_value_7 (load_update_value_6 (load_update_value_5 (load_update_value_4 (load_update_value_3 (load_update_value_2 (load_update_value_1 (load_update_value_0 old (f 0%N)) (bv_extract 8%N 8 old)) (bv_extract 16%N 8 old)) (bv_extract 24%N 8 old)) (bv_extract 32%N 8 old)) (bv_extract 40%N 8 old)) (bv_extract 48%N 8 old)) (bv_extract 56%N 8 old)) (bv_extract 64%N 8 old)) (bv_extract 72%N 8 old)) (bv_extract 80%N 8 old)) (bv_extract 88%N 8 old)) (bv_extract 96%N 8 old)) (bv_extract 104%N 8 old)) (bv_extract 112%N 8 old)) (bv_extract 120%N 8 old)) (bv_extract 128%N 8 old)) (bv_extract 136%N 8 old)) (bv_extract 144%N 8 old)) (bv_extract 152%N 8 old)) (bv_extract 160%N 8 old)) (bv_extract 168%N 8 old)) (bv_extract 176%N 8 old)) (bv_extract 184%N 8 old)) (bv_extract 192%N 8 old)) (bv_extract 200%N 8 old)) (bv_extract 208%N 8 old)) (bv_extract 216%N 8 old)) (bv_extract 224%N 8 old)) (bv_extract 232%N 8 old)) (bv_extract 240%N 8 old)) (bv_extract 248%N 8 old)) = loaded8 (BV 64 1) old f.
Proof. rewrite <- load_all_updates_correct_fast. reflexivity. Qed.
Print Assumptions load_case_value_1.
Lemma load_case_value_2 old (f : N -> bv 8) :
 (load_update_value_31 (load_update_value_30 (load_update_value_29 (load_update_value_28 (load_update_value_27 (load_update_value_26 (load_update_value_25 (load_update_value_24 (load_update_value_23 (load_update_value_22 (load_update_value_21 (load_update_value_20 (load_update_value_19 (load_update_value_18 (load_update_value_17 (load_update_value_16 (load_update_value_15 (load_update_value_14 (load_update_value_13 (load_update_value_12 (load_update_value_11 (load_update_value_10 (load_update_value_9 (load_update_value_8 (load_update_value_7 (load_update_value_6 (load_update_value_5 (load_update_value_4 (load_update_value_3 (load_update_value_2 (load_update_value_1 (load_update_value_0 old (f 0%N)) (f 1%N)) (bv_extract 16%N 8 old)) (bv_extract 24%N 8 old)) (bv_extract 32%N 8 old)) (bv_extract 40%N 8 old)) (bv_extract 48%N 8 old)) (bv_extract 56%N 8 old)) (bv_extract 64%N 8 old)) (bv_extract 72%N 8 old)) (bv_extract 80%N 8 old)) (bv_extract 88%N 8 old)) (bv_extract 96%N 8 old)) (bv_extract 104%N 8 old)) (bv_extract 112%N 8 old)) (bv_extract 120%N 8 old)) (bv_extract 128%N 8 old)) (bv_extract 136%N 8 old)) (bv_extract 144%N 8 old)) (bv_extract 152%N 8 old)) (bv_extract 160%N 8 old)) (bv_extract 168%N 8 old)) (bv_extract 176%N 8 old)) (bv_extract 184%N 8 old)) (bv_extract 192%N 8 old)) (bv_extract 200%N 8 old)) (bv_extract 208%N 8 old)) (bv_extract 216%N 8 old)) (bv_extract 224%N 8 old)) (bv_extract 232%N 8 old)) (bv_extract 240%N 8 old)) (bv_extract 248%N 8 old)) = loaded8 (BV 64 2) old f.
Proof. rewrite <- load_all_updates_correct_fast. reflexivity. Qed.
Print Assumptions load_case_value_2.
Lemma load_case_value_3 old (f : N -> bv 8) :
 (load_update_value_31 (load_update_value_30 (load_update_value_29 (load_update_value_28 (load_update_value_27 (load_update_value_26 (load_update_value_25 (load_update_value_24 (load_update_value_23 (load_update_value_22 (load_update_value_21 (load_update_value_20 (load_update_value_19 (load_update_value_18 (load_update_value_17 (load_update_value_16 (load_update_value_15 (load_update_value_14 (load_update_value_13 (load_update_value_12 (load_update_value_11 (load_update_value_10 (load_update_value_9 (load_update_value_8 (load_update_value_7 (load_update_value_6 (load_update_value_5 (load_update_value_4 (load_update_value_3 (load_update_value_2 (load_update_value_1 (load_update_value_0 old (f 0%N)) (f 1%N)) (f 2%N)) (bv_extract 24%N 8 old)) (bv_extract 32%N 8 old)) (bv_extract 40%N 8 old)) (bv_extract 48%N 8 old)) (bv_extract 56%N 8 old)) (bv_extract 64%N 8 old)) (bv_extract 72%N 8 old)) (bv_extract 80%N 8 old)) (bv_extract 88%N 8 old)) (bv_extract 96%N 8 old)) (bv_extract 104%N 8 old)) (bv_extract 112%N 8 old)) (bv_extract 120%N 8 old)) (bv_extract 128%N 8 old)) (bv_extract 136%N 8 old)) (bv_extract 144%N 8 old)) (bv_extract 152%N 8 old)) (bv_extract 160%N 8 old)) (bv_extract 168%N 8 old)) (bv_extract 176%N 8 old)) (bv_extract 184%N 8 old)) (bv_extract 192%N 8 old)) (bv_extract 200%N 8 old)) (bv_extract 208%N 8 old)) (bv_extract 216%N 8 old)) (bv_extract 224%N 8 old)) (bv_extract 232%N 8 old)) (bv_extract 240%N 8 old)) (bv_extract 248%N 8 old)) = loaded8 (BV 64 3) old f.
Proof. rewrite <- load_all_updates_correct_fast. reflexivity. Qed.
Print Assumptions load_case_value_3.
Lemma load_case_value_4 old (f : N -> bv 8) :
 (load_update_value_31 (load_update_value_30 (load_update_value_29 (load_update_value_28 (load_update_value_27 (load_update_value_26 (load_update_value_25 (load_update_value_24 (load_update_value_23 (load_update_value_22 (load_update_value_21 (load_update_value_20 (load_update_value_19 (load_update_value_18 (load_update_value_17 (load_update_value_16 (load_update_value_15 (load_update_value_14 (load_update_value_13 (load_update_value_12 (load_update_value_11 (load_update_value_10 (load_update_value_9 (load_update_value_8 (load_update_value_7 (load_update_value_6 (load_update_value_5 (load_update_value_4 (load_update_value_3 (load_update_value_2 (load_update_value_1 (load_update_value_0 old (f 0%N)) (f 1%N)) (f 2%N)) (f 3%N)) (bv_extract 32%N 8 old)) (bv_extract 40%N 8 old)) (bv_extract 48%N 8 old)) (bv_extract 56%N 8 old)) (bv_extract 64%N 8 old)) (bv_extract 72%N 8 old)) (bv_extract 80%N 8 old)) (bv_extract 88%N 8 old)) (bv_extract 96%N 8 old)) (bv_extract 104%N 8 old)) (bv_extract 112%N 8 old)) (bv_extract 120%N 8 old)) (bv_extract 128%N 8 old)) (bv_extract 136%N 8 old)) (bv_extract 144%N 8 old)) (bv_extract 152%N 8 old)) (bv_extract 160%N 8 old)) (bv_extract 168%N 8 old)) (bv_extract 176%N 8 old)) (bv_extract 184%N 8 old)) (bv_extract 192%N 8 old)) (bv_extract 200%N 8 old)) (bv_extract 208%N 8 old)) (bv_extract 216%N 8 old)) (bv_extract 224%N 8 old)) (bv_extract 232%N 8 old)) (bv_extract 240%N 8 old)) (bv_extract 248%N 8 old)) = loaded8 (BV 64 4) old f.
Proof. rewrite <- load_all_updates_correct_fast. reflexivity. Qed.
Print Assumptions load_case_value_4.
Lemma load_case_value_5 old (f : N -> bv 8) :
 (load_update_value_31 (load_update_value_30 (load_update_value_29 (load_update_value_28 (load_update_value_27 (load_update_value_26 (load_update_value_25 (load_update_value_24 (load_update_value_23 (load_update_value_22 (load_update_value_21 (load_update_value_20 (load_update_value_19 (load_update_value_18 (load_update_value_17 (load_update_value_16 (load_update_value_15 (load_update_value_14 (load_update_value_13 (load_update_value_12 (load_update_value_11 (load_update_value_10 (load_update_value_9 (load_update_value_8 (load_update_value_7 (load_update_value_6 (load_update_value_5 (load_update_value_4 (load_update_value_3 (load_update_value_2 (load_update_value_1 (load_update_value_0 old (f 0%N)) (f 1%N)) (f 2%N)) (f 3%N)) (f 4%N)) (bv_extract 40%N 8 old)) (bv_extract 48%N 8 old)) (bv_extract 56%N 8 old)) (bv_extract 64%N 8 old)) (bv_extract 72%N 8 old)) (bv_extract 80%N 8 old)) (bv_extract 88%N 8 old)) (bv_extract 96%N 8 old)) (bv_extract 104%N 8 old)) (bv_extract 112%N 8 old)) (bv_extract 120%N 8 old)) (bv_extract 128%N 8 old)) (bv_extract 136%N 8 old)) (bv_extract 144%N 8 old)) (bv_extract 152%N 8 old)) (bv_extract 160%N 8 old)) (bv_extract 168%N 8 old)) (bv_extract 176%N 8 old)) (bv_extract 184%N 8 old)) (bv_extract 192%N 8 old)) (bv_extract 200%N 8 old)) (bv_extract 208%N 8 old)) (bv_extract 216%N 8 old)) (bv_extract 224%N 8 old)) (bv_extract 232%N 8 old)) (bv_extract 240%N 8 old)) (bv_extract 248%N 8 old)) = loaded8 (BV 64 5) old f.
Proof. rewrite <- load_all_updates_correct_fast. reflexivity. Qed.
Print Assumptions load_case_value_5.
Lemma load_case_value_6 old (f : N -> bv 8) :
 (load_update_value_31 (load_update_value_30 (load_update_value_29 (load_update_value_28 (load_update_value_27 (load_update_value_26 (load_update_value_25 (load_update_value_24 (load_update_value_23 (load_update_value_22 (load_update_value_21 (load_update_value_20 (load_update_value_19 (load_update_value_18 (load_update_value_17 (load_update_value_16 (load_update_value_15 (load_update_value_14 (load_update_value_13 (load_update_value_12 (load_update_value_11 (load_update_value_10 (load_update_value_9 (load_update_value_8 (load_update_value_7 (load_update_value_6 (load_update_value_5 (load_update_value_4 (load_update_value_3 (load_update_value_2 (load_update_value_1 (load_update_value_0 old (f 0%N)) (f 1%N)) (f 2%N)) (f 3%N)) (f 4%N)) (f 5%N)) (bv_extract 48%N 8 old)) (bv_extract 56%N 8 old)) (bv_extract 64%N 8 old)) (bv_extract 72%N 8 old)) (bv_extract 80%N 8 old)) (bv_extract 88%N 8 old)) (bv_extract 96%N 8 old)) (bv_extract 104%N 8 old)) (bv_extract 112%N 8 old)) (bv_extract 120%N 8 old)) (bv_extract 128%N 8 old)) (bv_extract 136%N 8 old)) (bv_extract 144%N 8 old)) (bv_extract 152%N 8 old)) (bv_extract 160%N 8 old)) (bv_extract 168%N 8 old)) (bv_extract 176%N 8 old)) (bv_extract 184%N 8 old)) (bv_extract 192%N 8 old)) (bv_extract 200%N 8 old)) (bv_extract 208%N 8 old)) (bv_extract 216%N 8 old)) (bv_extract 224%N 8 old)) (bv_extract 232%N 8 old)) (bv_extract 240%N 8 old)) (bv_extract 248%N 8 old)) = loaded8 (BV 64 6) old f.
Proof. rewrite <- load_all_updates_correct_fast. reflexivity. Qed.
Print Assumptions load_case_value_6.
Lemma load_case_value_7 old (f : N -> bv 8) :
 (load_update_value_31 (load_update_value_30 (load_update_value_29 (load_update_value_28 (load_update_value_27 (load_update_value_26 (load_update_value_25 (load_update_value_24 (load_update_value_23 (load_update_value_22 (load_update_value_21 (load_update_value_20 (load_update_value_19 (load_update_value_18 (load_update_value_17 (load_update_value_16 (load_update_value_15 (load_update_value_14 (load_update_value_13 (load_update_value_12 (load_update_value_11 (load_update_value_10 (load_update_value_9 (load_update_value_8 (load_update_value_7 (load_update_value_6 (load_update_value_5 (load_update_value_4 (load_update_value_3 (load_update_value_2 (load_update_value_1 (load_update_value_0 old (f 0%N)) (f 1%N)) (f 2%N)) (f 3%N)) (f 4%N)) (f 5%N)) (f 6%N)) (bv_extract 56%N 8 old)) (bv_extract 64%N 8 old)) (bv_extract 72%N 8 old)) (bv_extract 80%N 8 old)) (bv_extract 88%N 8 old)) (bv_extract 96%N 8 old)) (bv_extract 104%N 8 old)) (bv_extract 112%N 8 old)) (bv_extract 120%N 8 old)) (bv_extract 128%N 8 old)) (bv_extract 136%N 8 old)) (bv_extract 144%N 8 old)) (bv_extract 152%N 8 old)) (bv_extract 160%N 8 old)) (bv_extract 168%N 8 old)) (bv_extract 176%N 8 old)) (bv_extract 184%N 8 old)) (bv_extract 192%N 8 old)) (bv_extract 200%N 8 old)) (bv_extract 208%N 8 old)) (bv_extract 216%N 8 old)) (bv_extract 224%N 8 old)) (bv_extract 232%N 8 old)) (bv_extract 240%N 8 old)) (bv_extract 248%N 8 old)) = loaded8 (BV 64 7) old f.
Proof. rewrite <- load_all_updates_correct_fast. reflexivity. Qed.
Print Assumptions load_case_value_7.
Lemma load_case_value_8 old (f : N -> bv 8) :
 (load_update_value_31 (load_update_value_30 (load_update_value_29 (load_update_value_28 (load_update_value_27 (load_update_value_26 (load_update_value_25 (load_update_value_24 (load_update_value_23 (load_update_value_22 (load_update_value_21 (load_update_value_20 (load_update_value_19 (load_update_value_18 (load_update_value_17 (load_update_value_16 (load_update_value_15 (load_update_value_14 (load_update_value_13 (load_update_value_12 (load_update_value_11 (load_update_value_10 (load_update_value_9 (load_update_value_8 (load_update_value_7 (load_update_value_6 (load_update_value_5 (load_update_value_4 (load_update_value_3 (load_update_value_2 (load_update_value_1 (load_update_value_0 old (f 0%N)) (f 1%N)) (f 2%N)) (f 3%N)) (f 4%N)) (f 5%N)) (f 6%N)) (f 7%N)) (bv_extract 64%N 8 old)) (bv_extract 72%N 8 old)) (bv_extract 80%N 8 old)) (bv_extract 88%N 8 old)) (bv_extract 96%N 8 old)) (bv_extract 104%N 8 old)) (bv_extract 112%N 8 old)) (bv_extract 120%N 8 old)) (bv_extract 128%N 8 old)) (bv_extract 136%N 8 old)) (bv_extract 144%N 8 old)) (bv_extract 152%N 8 old)) (bv_extract 160%N 8 old)) (bv_extract 168%N 8 old)) (bv_extract 176%N 8 old)) (bv_extract 184%N 8 old)) (bv_extract 192%N 8 old)) (bv_extract 200%N 8 old)) (bv_extract 208%N 8 old)) (bv_extract 216%N 8 old)) (bv_extract 224%N 8 old)) (bv_extract 232%N 8 old)) (bv_extract 240%N 8 old)) (bv_extract 248%N 8 old)) = loaded8 (BV 64 8) old f.
Proof. rewrite <- load_all_updates_correct_fast. reflexivity. Qed.
Print Assumptions load_case_value_8.
Ltac rewriteVectorValues :=
  repeat match goal with
  | H : vector_value_eq ?v ?value |- context [ ?v ] =>
    rewrite (vector_value_eq_elim v value H)
  end.
