#!/usr/bin/env python3
"""Copy two *unchanged* pure declarations from the recorded Sail-generated model.

This textual extraction is NOT a certified lifter. It neither imports execute,
nor asserts anything about decoder correctness, machine-state updates or loops.
"""
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT.parent / "vendor/lean-kernel/Rv64Kernel/VextVsetInsts.lean"


def main():
    text = SOURCE.read_text()
    start = text.index("def vl_use_ceil : Bool := false\n")
    end = text.index("/-- Type quantifiers:", text.index("def calculate_new_vl", start))
    declarations = text[start:end]
    target = ROOT / "SailVLExtract.lean"
    target.write_text(
        "/- Generated by extract_vl.py; do not edit. A source excerpt, NOT a full ISA model. -/\n"
        "import Sail\nopen PreSail Sail\nnamespace SailVLExtract\n\n"
        + declarations + "end SailVLExtract\n"
    )
    result = {
        "source": str(SOURCE.relative_to(ROOT.parent)),
        "source_sha256": hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
        "source_first_line": text[:start].count("\n") + 1,
        "declarations_sha256": hashlib.sha256(declarations.encode()).hexdigest(),
        "output_sha256": hashlib.sha256(target.read_bytes()).hexdigest(),
        "certified_extraction": False,
        "full_instruction_semantics": False,
    }
    (ROOT / "results/vl-extraction.json").write_text(json.dumps(result, indent=2) + "\n")
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
