/- Generated by extract_vl.py; do not edit. A source excerpt, NOT a full ISA model. -/
import Sail
open PreSail Sail
namespace SailVLExtract

def vl_use_ceil : Bool := false

/-- Type quantifiers: VLMAX : Nat, 1 ≤ VLMAX ∧ VLMAX ≤ (2 ^ 8) -/
def calculate_new_vl (AVL : (BitVec 64)) (VLMAX : Nat) : Nat :=
  let AVL := (BitVec.toNatInt AVL)
  if ((AVL ≤b VLMAX) : Bool)
  then AVL
  else
    (if ((AVL <b (2 *i VLMAX)) : Bool)
    then
      (if (vl_use_ceil : Bool)
      then (Int.tdiv (AVL +i 1) 2)
      else VLMAX)
    else VLMAX)

end SailVLExtract
