#!/usr/bin/env python3
"""Embed this experiment's ELF64 load segments and test_rvv bytes in Lean.

This imports data only. Instruction meanings come from Sail, not this script.
The script deliberately accepts only little-endian, linked RISC-V ELF64 files.
"""
import argparse
import hashlib
import json
from pathlib import Path
import struct


def convert(elf_path: Path, asm_path: Path, output: Path) -> None:
    data = elf_path.read_bytes()
    if data[:7] != b"\x7fELF\x02\x01\x01":
        raise ValueError("expected little-endian ELF64")
    header = struct.unpack_from("<HHIQQQIHHHHHH", data, 16)
    typ, machine, _, entry, phoff, shoff, _, _, phsize, phnum, shsize, shnum, _ = header
    if (typ, machine, phsize, shsize) != (2, 243, 56, 64):
        raise ValueError("expected linked RISC-V ELF64 with standard headers")

    def slice_at(offset, length):
        if offset < 0 or length < 0 or offset + length > len(data):
            raise ValueError("ELF range outside file")
        return data[offset:offset + length]

    sections = [struct.unpack("<IIQQQQIIQQ", slice_at(shoff + i * shsize, shsize))
                for i in range(shnum)]
    symbols = {}
    for sec in sections:
        if sec[1] != 2:  # SHT_SYMTAB
            continue
        if sec[9] != 24 or sec[5] % 24:
            raise ValueError("invalid symbol table entry size")
        strings = sections[sec[6]]
        names = slice_at(strings[4], strings[5])
        for pos in range(sec[4], sec[4] + sec[5], 24):
            name, _, _, index, value, size = struct.unpack("<IBBHQQ", slice_at(pos, 24))
            end = names.index(0, name)
            symbols[names[name:end].decode()] = (index, value, size)
    index, address, size = symbols["test_rvv"]
    if not size or not 0 < index < len(sections):
        raise ValueError("test_rvv must be a defined, nonempty function")
    sec = sections[index]
    delta = address - sec[3]
    if not 0 <= delta <= sec[5] - size:
        raise ValueError("function lies outside its section")
    target = slice_at(sec[4] + delta, size)

    segments = []
    for i in range(phnum):
        pt, flags, offset, virtual, physical, filesz, memsz, _ = struct.unpack(
            "<IIQQQQQQ", slice_at(phoff + i * phsize, phsize))
        if pt != 1:
            continue
        if virtual != physical or filesz > memsz:
            raise ValueError("unsupported segment layout")
        segments.append((virtual, memsz, flags, slice_at(offset, filesz)))

    def literal(bs):
        lines = [", ".join(f"0x{x:02x}" for x in bs[i:i + 16])
                 for i in range(0, len(bs), 16)]
        return "#[\n    " + ",\n    ".join(lines) + "\n  ]"

    asm_sha = hashlib.sha256(asm_path.read_bytes()).hexdigest()
    elf_sha = hashlib.sha256(data).hexdigest()
    text = ["-- Generated by elf-to-lean.py; program data, not handwritten ISA semantics.",
            "import Std", "namespace RvvProgram", "",
            f'def assemblySha256 : String := "{asm_sha}"',
            f'def elfSha256 : String := "{elf_sha}"',
            f"def entryPoint : Nat := 0x{entry:x}",
            f"def targetAddress : Nat := 0x{address:x}",
            f"def tohostAddress : Nat := 0x{symbols['tohost'][1]:x}",
            f"def targetBytes : Array UInt8 := {literal(target)}", "",
            "structure Segment where", "  address : Nat", "  memorySize : Nat",
            "  bytes : Array UInt8", "", "def segments : List Segment := ["]
    for n, (addr, memsz, _, bs) in enumerate(segments):
        text.append(f"  ⟨0x{addr:x}, {memsz}, {literal(bs)}⟩" +
                    ("," if n + 1 < len(segments) else ""))
    text += ["]", "", "end RvvProgram", ""]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(text))
    manifest = dict(assembly_sha256=asm_sha, elf_sha256=elf_sha, entry=entry,
                    target_address=address, target_size=size, target_bytes=target.hex(),
                    tohost=symbols['tohost'][1],
                    segments=[dict(address=a, memory_size=m, flags=f, file_size=len(b))
                              for a, m, f, b in segments])
    output.with_suffix(".json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"Embedded {len(segments)} segments; test_rvv: {size} bytes at 0x{address:x}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("elf", type=Path)
    parser.add_argument("assembly", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    convert(args.elf, args.assembly, args.output)
