opam-version: "2.0"
synopsis: "Coq proofs for NEON byte reduction and RVV instructions"
maintainer: "SALTy-rn contributors"
authors: ["SALTy-rn contributors"]
homepage: "https://github.com/Etha-Sun/SALTy-rn"
bug-reports: "https://github.com/Etha-Sun/SALTy-rn/issues"
depends: [
  "ocaml" {= "4.14.2"}
  "coq" {= "8.19.0"}
  "coq-iris" {= "dev.2024-09-10.1.6f24ed4b"}
  "coq-lithium" {= "dev.2024-09-11.0.7945a29d"}
  "coq-stdpp" {= "dev.2024-09-10.3.a1a12e00"}
  "coq-stdpp-bitvector" {= "dev.2024-09-10.3.a1a12e00"}
  "coq-stdpp-unstable" {= "dev.2024-09-10.3.a1a12e00"}
  "coq-record-update" {= "0.3.3"}
  "isla-lang" {= "dev"}
  "dune" {= "3.9.1"}
  "menhir" {= "20260209"}
  "ott" {= "0.34"}
  "pprint" {= "20230830"}
  "cmdliner" {= "2.1.1"}
  "integers" {= "0.8.0"}
  "conf-gmp"
]
pin-depends: [
  ["coq-iris.dev.2024-09-10.1.6f24ed4b" "git+https://gitlab.mpi-sws.org/iris/iris.git#6f24ed4baa4d61967a95bac834eab2c66f3b76fa"]
  ["coq-lithium.dev.2024-09-11.0.7945a29d" "git+https://gitlab.mpi-sws.org/iris/refinedc.git#7945a29d1647970709a9b5ad2ffc53c757e130cc"]
  ["coq-stdpp.dev.2024-09-10.3.a1a12e00" "git+https://gitlab.mpi-sws.org/iris/stdpp.git#a1a12e00fba07f2e41ccd74a8b593b88e48fc2c3"]
  ["coq-stdpp-bitvector.dev.2024-09-10.3.a1a12e00" "git+https://gitlab.mpi-sws.org/iris/stdpp.git#a1a12e00fba07f2e41ccd74a8b593b88e48fc2c3"]
  ["coq-stdpp-unstable.dev.2024-09-10.3.a1a12e00" "git+https://gitlab.mpi-sws.org/iris/stdpp.git#a1a12e00fba07f2e41ccd74a8b593b88e48fc2c3"]
  ["isla-lang.dev" "git+https://github.com/rems-project/isla-lang.git#bda86c9f0bd28bbaa2481f50ddc986ede342805a"]
]
build: [ [make "-j" jobs] ]
install: [ [make "install"] ]
