-- Generated by tools/extract_u8_vclamp.py. Do not hand-edit.
import Neon2LeanDemo.IR

namespace Neon2LeanDemo.Generated

def extractedSource : SourceInfo :=
  { path := "kernels/source/u8-vclamp.c"
    sha256 := "e52c7c97805aec65922f07f19c7496015596e375b17306258f9e5f4805528f57"
    beginOffset := 499
    endOffset := 1260 }

def u8VClampBlock0 : Store 16 8 :=
  { outputOffset := 0
    value :=
      .bin (.min .unsigned)
        (.bin (.max .unsigned)
            (.load 0)
            (.splat (.paramU32Trunc "min")))
        (.splat (.paramU32Trunc "max")) }

def u8VClampBlock1 : Store 16 8 :=
  { outputOffset := 16
    value :=
      .bin (.min .unsigned)
        (.bin (.max .unsigned)
            (.load 16)
            (.splat (.paramU32Trunc "min")))
        (.splat (.paramU32Trunc "max")) }

def u8VClampBlock2 : Store 16 8 :=
  { outputOffset := 32
    value :=
      .bin (.min .unsigned)
        (.bin (.max .unsigned)
            (.load 32)
            (.splat (.paramU32Trunc "min")))
        (.splat (.paramU32Trunc "max")) }

def u8VClampBlock3 : Store 16 8 :=
  { outputOffset := 48
    value :=
      .bin (.min .unsigned)
        (.bin (.max .unsigned)
            (.load 48)
            (.splat (.paramU32Trunc "min")))
        (.splat (.paramU32Trunc "max")) }

def u8VClampMain : FixedLoop 16 8 :=
  { source := extractedSource
    batchGuard := 64
    batchDecrement := 64
    inputAdvance := 64
    outputAdvance := 64
    stores :=
      [u8VClampBlock0,
       u8VClampBlock1,
       u8VClampBlock2,
       u8VClampBlock3] }

end Neon2LeanDemo.Generated
