#pragma once
// RVV integer reductions — generated (ns salt). result lane0 = fold(init[0], vec[i]); tail = init tail.
#include "../intrinsics.hpp"
namespace salt {
enum RedOp { R_ADD,R_AND,R_OR,R_XOR,R_SMAX,R_UMAX,R_SMIN,R_UMIN,R_WSUMS,R_WSUMU };
inline RVVVector _gred(const RVVVector& vec,const RVVVector& init,size_t vbits,size_t rbits,RedOp op,size_t vl){
  auto& tm=g_ctx->tm; Term acc=init.getElement(0);
  for(size_t i=0;i<vl;i++){
    Term e=vec.getElement(i);
    switch(op){
      case R_ADD: acc=tm.mk_term(Kind::BV_ADD,{acc,e}); break;
      case R_AND: acc=tm.mk_term(Kind::BV_AND,{acc,e}); break;
      case R_OR:  acc=tm.mk_term(Kind::BV_OR,{acc,e}); break;
      case R_XOR: acc=tm.mk_term(Kind::BV_XOR,{acc,e}); break;
      case R_SMAX:acc=fold_ite(tm,tm.mk_term(Kind::BV_SGE,{acc,e}),acc,e); break;
      case R_UMAX:acc=fold_ite(tm,tm.mk_term(Kind::BV_UGE,{acc,e}),acc,e); break;
      case R_SMIN:acc=fold_ite(tm,tm.mk_term(Kind::BV_SLE,{acc,e}),acc,e); break;
      case R_UMIN:acc=fold_ite(tm,tm.mk_term(Kind::BV_ULE,{acc,e}),acc,e); break;
      case R_WSUMS:acc=tm.mk_term(Kind::BV_ADD,{acc,fold_bvsext(tm,rbits-vbits,e)}); break;
      case R_WSUMU:acc=tm.mk_term(Kind::BV_ADD,{acc,fold_bvzext(tm,rbits-vbits,e)}); break;
    }
  }
  std::vector<Term> r; r.reserve(init.getVL()); r.push_back(acc);
  for(size_t i=1;i<init.getVL();i++) r.push_back(init.getElement(i));
  return RVVVector(tm,rbits,r);
}
inline RVVVector __riscv_vredand_vs_i16m1_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_i16m2_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_i16m4_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_i16m8_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_i16mf2_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_i16mf4_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_i32m1_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_i32m2_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_i32m4_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_i32m8_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_i32mf2_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_i64m1_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_i64m2_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_i64m4_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_i64m8_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_i8m1_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_i8m2_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_i8m4_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_i8m8_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_i8mf2_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_i8mf4_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_i8mf8_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_u16m1_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_u16m2_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_u16m4_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_u16m8_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_u16mf2_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_u16mf4_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_u32m1_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_u32m2_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_u32m4_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_u32m8_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_u32mf2_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_u64m1_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_u64m2_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_u64m4_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_u64m8_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_u8m1_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_u8m2_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_u8m4_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_u8m8_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_u8mf2_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_u8mf4_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_AND,vl); }
inline RVVVector __riscv_vredand_vs_u8mf8_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_AND,vl); }
inline RVVVector __riscv_vredmax_vs_i16m1_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_SMAX,vl); }
inline RVVVector __riscv_vredmax_vs_i16m2_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_SMAX,vl); }
inline RVVVector __riscv_vredmax_vs_i16m4_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_SMAX,vl); }
inline RVVVector __riscv_vredmax_vs_i16m8_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_SMAX,vl); }
inline RVVVector __riscv_vredmax_vs_i16mf2_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_SMAX,vl); }
inline RVVVector __riscv_vredmax_vs_i16mf4_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_SMAX,vl); }
inline RVVVector __riscv_vredmax_vs_i32m1_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_SMAX,vl); }
inline RVVVector __riscv_vredmax_vs_i32m2_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_SMAX,vl); }
inline RVVVector __riscv_vredmax_vs_i32m4_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_SMAX,vl); }
inline RVVVector __riscv_vredmax_vs_i32m8_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_SMAX,vl); }
inline RVVVector __riscv_vredmax_vs_i32mf2_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_SMAX,vl); }
inline RVVVector __riscv_vredmax_vs_i64m1_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_SMAX,vl); }
inline RVVVector __riscv_vredmax_vs_i64m2_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_SMAX,vl); }
inline RVVVector __riscv_vredmax_vs_i64m4_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_SMAX,vl); }
inline RVVVector __riscv_vredmax_vs_i64m8_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_SMAX,vl); }
inline RVVVector __riscv_vredmax_vs_i8m1_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_SMAX,vl); }
inline RVVVector __riscv_vredmax_vs_i8m2_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_SMAX,vl); }
inline RVVVector __riscv_vredmax_vs_i8m4_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_SMAX,vl); }
inline RVVVector __riscv_vredmax_vs_i8m8_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_SMAX,vl); }
inline RVVVector __riscv_vredmax_vs_i8mf2_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_SMAX,vl); }
inline RVVVector __riscv_vredmax_vs_i8mf4_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_SMAX,vl); }
inline RVVVector __riscv_vredmax_vs_i8mf8_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_SMAX,vl); }
inline RVVVector __riscv_vredmaxu_vs_u16m1_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_UMAX,vl); }
inline RVVVector __riscv_vredmaxu_vs_u16m2_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_UMAX,vl); }
inline RVVVector __riscv_vredmaxu_vs_u16m4_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_UMAX,vl); }
inline RVVVector __riscv_vredmaxu_vs_u16m8_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_UMAX,vl); }
inline RVVVector __riscv_vredmaxu_vs_u16mf2_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_UMAX,vl); }
inline RVVVector __riscv_vredmaxu_vs_u16mf4_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_UMAX,vl); }
inline RVVVector __riscv_vredmaxu_vs_u32m1_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_UMAX,vl); }
inline RVVVector __riscv_vredmaxu_vs_u32m2_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_UMAX,vl); }
inline RVVVector __riscv_vredmaxu_vs_u32m4_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_UMAX,vl); }
inline RVVVector __riscv_vredmaxu_vs_u32m8_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_UMAX,vl); }
inline RVVVector __riscv_vredmaxu_vs_u32mf2_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_UMAX,vl); }
inline RVVVector __riscv_vredmaxu_vs_u64m1_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_UMAX,vl); }
inline RVVVector __riscv_vredmaxu_vs_u64m2_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_UMAX,vl); }
inline RVVVector __riscv_vredmaxu_vs_u64m4_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_UMAX,vl); }
inline RVVVector __riscv_vredmaxu_vs_u64m8_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_UMAX,vl); }
inline RVVVector __riscv_vredmaxu_vs_u8m1_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_UMAX,vl); }
inline RVVVector __riscv_vredmaxu_vs_u8m2_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_UMAX,vl); }
inline RVVVector __riscv_vredmaxu_vs_u8m4_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_UMAX,vl); }
inline RVVVector __riscv_vredmaxu_vs_u8m8_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_UMAX,vl); }
inline RVVVector __riscv_vredmaxu_vs_u8mf2_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_UMAX,vl); }
inline RVVVector __riscv_vredmaxu_vs_u8mf4_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_UMAX,vl); }
inline RVVVector __riscv_vredmaxu_vs_u8mf8_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_UMAX,vl); }
inline RVVVector __riscv_vredmin_vs_i16m1_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_SMIN,vl); }
inline RVVVector __riscv_vredmin_vs_i16m2_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_SMIN,vl); }
inline RVVVector __riscv_vredmin_vs_i16m4_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_SMIN,vl); }
inline RVVVector __riscv_vredmin_vs_i16m8_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_SMIN,vl); }
inline RVVVector __riscv_vredmin_vs_i16mf2_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_SMIN,vl); }
inline RVVVector __riscv_vredmin_vs_i16mf4_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_SMIN,vl); }
inline RVVVector __riscv_vredmin_vs_i32m1_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_SMIN,vl); }
inline RVVVector __riscv_vredmin_vs_i32m2_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_SMIN,vl); }
inline RVVVector __riscv_vredmin_vs_i32m4_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_SMIN,vl); }
inline RVVVector __riscv_vredmin_vs_i32m8_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_SMIN,vl); }
inline RVVVector __riscv_vredmin_vs_i32mf2_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_SMIN,vl); }
inline RVVVector __riscv_vredmin_vs_i64m1_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_SMIN,vl); }
inline RVVVector __riscv_vredmin_vs_i64m2_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_SMIN,vl); }
inline RVVVector __riscv_vredmin_vs_i64m4_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_SMIN,vl); }
inline RVVVector __riscv_vredmin_vs_i64m8_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_SMIN,vl); }
inline RVVVector __riscv_vredmin_vs_i8m1_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_SMIN,vl); }
inline RVVVector __riscv_vredmin_vs_i8m2_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_SMIN,vl); }
inline RVVVector __riscv_vredmin_vs_i8m4_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_SMIN,vl); }
inline RVVVector __riscv_vredmin_vs_i8m8_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_SMIN,vl); }
inline RVVVector __riscv_vredmin_vs_i8mf2_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_SMIN,vl); }
inline RVVVector __riscv_vredmin_vs_i8mf4_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_SMIN,vl); }
inline RVVVector __riscv_vredmin_vs_i8mf8_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_SMIN,vl); }
inline RVVVector __riscv_vredminu_vs_u16m1_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_UMIN,vl); }
inline RVVVector __riscv_vredminu_vs_u16m2_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_UMIN,vl); }
inline RVVVector __riscv_vredminu_vs_u16m4_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_UMIN,vl); }
inline RVVVector __riscv_vredminu_vs_u16m8_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_UMIN,vl); }
inline RVVVector __riscv_vredminu_vs_u16mf2_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_UMIN,vl); }
inline RVVVector __riscv_vredminu_vs_u16mf4_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_UMIN,vl); }
inline RVVVector __riscv_vredminu_vs_u32m1_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_UMIN,vl); }
inline RVVVector __riscv_vredminu_vs_u32m2_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_UMIN,vl); }
inline RVVVector __riscv_vredminu_vs_u32m4_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_UMIN,vl); }
inline RVVVector __riscv_vredminu_vs_u32m8_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_UMIN,vl); }
inline RVVVector __riscv_vredminu_vs_u32mf2_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_UMIN,vl); }
inline RVVVector __riscv_vredminu_vs_u64m1_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_UMIN,vl); }
inline RVVVector __riscv_vredminu_vs_u64m2_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_UMIN,vl); }
inline RVVVector __riscv_vredminu_vs_u64m4_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_UMIN,vl); }
inline RVVVector __riscv_vredminu_vs_u64m8_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_UMIN,vl); }
inline RVVVector __riscv_vredminu_vs_u8m1_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_UMIN,vl); }
inline RVVVector __riscv_vredminu_vs_u8m2_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_UMIN,vl); }
inline RVVVector __riscv_vredminu_vs_u8m4_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_UMIN,vl); }
inline RVVVector __riscv_vredminu_vs_u8m8_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_UMIN,vl); }
inline RVVVector __riscv_vredminu_vs_u8mf2_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_UMIN,vl); }
inline RVVVector __riscv_vredminu_vs_u8mf4_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_UMIN,vl); }
inline RVVVector __riscv_vredminu_vs_u8mf8_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_UMIN,vl); }
inline RVVVector __riscv_vredor_vs_i16m1_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_i16m2_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_i16m4_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_i16m8_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_i16mf2_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_i16mf4_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_i32m1_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_i32m2_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_i32m4_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_i32m8_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_i32mf2_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_i64m1_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_i64m2_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_i64m4_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_i64m8_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_i8m1_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_i8m2_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_i8m4_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_i8m8_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_i8mf2_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_i8mf4_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_i8mf8_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_u16m1_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_u16m2_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_u16m4_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_u16m8_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_u16mf2_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_u16mf4_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_u32m1_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_u32m2_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_u32m4_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_u32m8_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_u32mf2_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_u64m1_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_u64m2_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_u64m4_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_u64m8_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_u8m1_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_u8m2_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_u8m4_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_u8m8_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_u8mf2_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_u8mf4_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_OR,vl); }
inline RVVVector __riscv_vredor_vs_u8mf8_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_OR,vl); }
inline RVVVector __riscv_vredsum_vs_i16m1_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_i16m2_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_i16m4_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_i16m8_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_i16mf2_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_i16mf4_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_i32m2_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_i32mf2_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_i64m1_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_i64m2_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_i64m4_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_i64m8_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_i8m1_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_i8m2_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_i8m4_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_i8m8_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_i8mf2_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_i8mf4_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_i8mf8_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_u16m1_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_u16m2_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_u16m4_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_u16m8_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_u16mf2_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_u16mf4_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_u32m1_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_u32m2_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_u32m4_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_u32m8_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_u32mf2_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_u64m1_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_u64m2_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_u64m4_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_u64m8_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_u8m1_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_u8m2_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_u8m4_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_u8m8_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_u8mf2_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_u8mf4_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_ADD,vl); }
inline RVVVector __riscv_vredsum_vs_u8mf8_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_ADD,vl); }
inline RVVVector __riscv_vredxor_vs_i16m1_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_i16m2_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_i16m4_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_i16m8_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_i16mf2_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_i16mf4_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_i32m1_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_i32m2_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_i32m4_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_i32m8_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_i32mf2_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_i64m1_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_i64m2_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_i64m4_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_i64m8_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_i8m1_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_i8m2_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_i8m4_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_i8m8_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_i8mf2_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_i8mf4_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_i8mf8_i8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_u16m1_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_u16m2_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_u16m4_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_u16m8_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_u16mf2_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_u16mf4_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,16,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_u32m1_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_u32m2_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_u32m4_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_u32m8_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_u32mf2_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,32,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_u64m1_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_u64m2_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_u64m4_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_u64m8_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,64,64,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_u8m1_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_u8m2_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_u8m4_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_u8m8_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_u8mf2_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_u8mf4_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_XOR,vl); }
inline RVVVector __riscv_vredxor_vs_u8mf8_u8m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,8,R_XOR,vl); }
inline RVVVector __riscv_vwredsum_vs_i16m1_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,32,R_WSUMS,vl); }
inline RVVVector __riscv_vwredsum_vs_i16m8_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,32,R_WSUMS,vl); }
inline RVVVector __riscv_vwredsum_vs_i16mf2_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,32,R_WSUMS,vl); }
inline RVVVector __riscv_vwredsum_vs_i16mf4_i32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,32,R_WSUMS,vl); }
inline RVVVector __riscv_vwredsum_vs_i32m1_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,64,R_WSUMS,vl); }
inline RVVVector __riscv_vwredsum_vs_i32m2_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,64,R_WSUMS,vl); }
inline RVVVector __riscv_vwredsum_vs_i32m4_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,64,R_WSUMS,vl); }
inline RVVVector __riscv_vwredsum_vs_i32m8_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,64,R_WSUMS,vl); }
inline RVVVector __riscv_vwredsum_vs_i32mf2_i64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,64,R_WSUMS,vl); }
inline RVVVector __riscv_vwredsum_vs_i8m1_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,16,R_WSUMS,vl); }
inline RVVVector __riscv_vwredsum_vs_i8m2_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,16,R_WSUMS,vl); }
inline RVVVector __riscv_vwredsum_vs_i8m4_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,16,R_WSUMS,vl); }
inline RVVVector __riscv_vwredsum_vs_i8m8_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,16,R_WSUMS,vl); }
inline RVVVector __riscv_vwredsum_vs_i8mf2_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,16,R_WSUMS,vl); }
inline RVVVector __riscv_vwredsum_vs_i8mf4_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,16,R_WSUMS,vl); }
inline RVVVector __riscv_vwredsum_vs_i8mf8_i16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,16,R_WSUMS,vl); }
inline RVVVector __riscv_vwredsumu_vs_u16m1_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,32,R_WSUMU,vl); }
inline RVVVector __riscv_vwredsumu_vs_u16m2_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,32,R_WSUMU,vl); }
inline RVVVector __riscv_vwredsumu_vs_u16m4_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,32,R_WSUMU,vl); }
inline RVVVector __riscv_vwredsumu_vs_u16m8_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,32,R_WSUMU,vl); }
inline RVVVector __riscv_vwredsumu_vs_u16mf2_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,32,R_WSUMU,vl); }
inline RVVVector __riscv_vwredsumu_vs_u16mf4_u32m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,16,32,R_WSUMU,vl); }
inline RVVVector __riscv_vwredsumu_vs_u32m1_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,64,R_WSUMU,vl); }
inline RVVVector __riscv_vwredsumu_vs_u32m2_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,64,R_WSUMU,vl); }
inline RVVVector __riscv_vwredsumu_vs_u32m4_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,64,R_WSUMU,vl); }
inline RVVVector __riscv_vwredsumu_vs_u32m8_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,64,R_WSUMU,vl); }
inline RVVVector __riscv_vwredsumu_vs_u32mf2_u64m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,32,64,R_WSUMU,vl); }
inline RVVVector __riscv_vwredsumu_vs_u8m1_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,16,R_WSUMU,vl); }
inline RVVVector __riscv_vwredsumu_vs_u8m2_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,16,R_WSUMU,vl); }
inline RVVVector __riscv_vwredsumu_vs_u8m4_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,16,R_WSUMU,vl); }
inline RVVVector __riscv_vwredsumu_vs_u8m8_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,16,R_WSUMU,vl); }
inline RVVVector __riscv_vwredsumu_vs_u8mf2_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,16,R_WSUMU,vl); }
inline RVVVector __riscv_vwredsumu_vs_u8mf4_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,16,R_WSUMU,vl); }
inline RVVVector __riscv_vwredsumu_vs_u8mf8_u16m1(const RVVVector& vec, const RVVVector& init, size_t vl){ return _gred(vec,init,8,16,R_WSUMU,vl); }
} // namespace salt
